export const KARTON_LIST_REQUEST = "KARTON_LIST_REQUEST";
export const KARTON_LIST_SUCCESS = "KARTON_LIST_SUCCESS";
export const KARTON_LIST_FAIL = "KARTON_LIST_FAIL";



export const KARTON_PACIJENTA_LIST_REQUEST = "KARTON_PACIJENTA_LIST_REQUEST";
export const KARTON_PACIJENTA_LIST_SUCCESS = "KARTON_PACIJENTA_LIST_SUCCESS";
export const KARTON_PACIJENTA_LIST_FAIL = "KARTON_PACIJENTA__LIST_FAIL";



