export const KORISNICKI_LOGIN_REQUEST = "KORISNICKI_LOGIN_REQUEST";
export const KORISNICKI_LOGIN_SUCCESS = "KORISNICKI_LOGIN_SUCCESS";
export const KORISNICKI_LOGIN_FAIL = "KORISNICKI_LOGIN_FAIL";
export const KORISNCIKI_LOGOUT = "KORISNICKI_LOGOUT";

export const DODAJ_KORISNIKA_REQUEST = "DODAJ_KORISNIKA_REQUEST";
export const DODAJ_KORISNIKA_SUCCESS = "DODAJ_KORISNIKA_SUCCESS";
export const DODAJ_KORISNIKA_FAIL = "DODAJ_KORISNIKA_FAIL";

export const UKLONI_KORISNIKA_REQUEST = "UKLONI_KORISNIKA_REQUEST";
export const UKLONI_KORISNIKA_SUCCESS = "UKLONI_KORISNIKA_SUCCESS";
export const UKLONI_KORISNIKA_FAIL = "UKLONI_KORISNIKA_FAIL";

export const KORISNICI_LIST_REQUEST = "KORISNICI_LIST_REQUEST";
export const KORISNICI_LIST_SUCCESS = "KORISNICI_LIST_SUCCESS";
export const KORISNICI_LIST_FAIL = "KORISNICI_LIST_FAIL";

export const LEKAR_LIST_REQUEST = "LEKAR_LIST_REQUEST";
export const LEKAR_LIST_SUCCESS = "LEKAR_LIST_SUCCESS";
export const LEKAR_LIST_FAIL = "LEKAR_LIST_FAIL";
