export const NAPOMENA_CREATE_REQUEST = "NAPOMENA_CREATE_REQUEST";
export const NAPOMENA_CREATE_SUCCESS = "NAPOMENA_CREATE_SUCCESS";
export const NAPOMENA_CREATE_RESET = "NAPOMENA_CREATE_RESET";
export const NAPOMENA_CREATE_FAIL = "NAPOMENA_CREATE_FAIL";
