
export const ODELJENJA_LIST_REQUEST="ODELJENJA_LIST_REQUEST"
export const ODELJENJA_LIST_SUCCESS="ODELJENJA_LIST_SUCCESS"
export const ODELJENJA_LIST_FAIL="ODELJENJA_LIST_FAIL"


export const ODELJENJA_DETAILS_REQUEST="ODELJENJA_DETAILS_REQUEST"
export const ODELJENJA_DETAILS_SUCCESS="ODELJENJA_DETAILS_SUCCESS"
export const ODELJENJA_DETAILS_FAIL="ODELJENJA_DETAILS_FAIL"





export const ODELJENJE_DELETE_REQUEST="ODELJENJA_DELETE_REQUEST"
export const ODELJENJE_DELETE_SUCCESS="ODELJENJA_DELETE_SUCCESS"
export const ODELJENJE_DELETE_FAIL="ODELJENJA_DELETE_FAIL"



export const ODELJENJE_CREATE_REQUEST="ODELJENJA_CREATE_REQUEST"
export const ODELJENJE_CREATE_SUCCESS="ODELJENJA_CREATE_SUCCESS"
export const ODELJENJE_CREATE_RESET="ODELJENJA_CREATE_RESET"
export const ODELJENJE_CREATE_FAIL="ODELJENJA_CREATE_FAIL"





export const ODELJENJE_UPDATE_REQUEST="ODELJENJA_UPDATE_REQUEST"
export const ODELJENJE_UPDATE_SUCCESS="ODELJENJA_UPDATE_SUCCESS"
export const ODELJENJE_UPDATE_RESET="ODELJENJA_UPDATE_RESET"
export const ODELJENJE_UPDATE_FAIL="ODELJENJA_UPDATE_FAIL"