export const PACIJENT_ODELJENJA_LIST_REQUEST = "PACIJENT_ODELJENJA_LIST_REQUEST";
export const PACIJENT_ODELJENJA_LIST_SUCCESS = "PACIJENT_ODELJENJA_LIST_SUCCESS";
export const PACIJENT_ODELJENJA_LIST_FAIL = "PACIJENT_ODELJENJA_LIST_FAIL";




export const PACIJENT_DETAILS_REQUEST = "PACIJENT_DETAILS_REQUEST";
export const PACIJENT_DETAILS_SUCCESS = "PACIJENT_DETAILS_SUCCESS";
export const PACIJENT_DETAILS_FAIL = "PACIJENT_DETAILS_FAIL";