export const PACIJENT_ODELJENJA_LIST_REQUEST = "PACIJENT_ODELJENJA_LIST_REQUEST";
export const PACIJENT_ODELJENJA_LIST_SUCCESS = "PACIJENT_ODELJENJA_LIST_SUCCESS";
export const PACIJENT_ODELJENJA_LIST_FAIL = "PACIJENT_ODELJENJA_LIST_FAIL";

export const PACIJENT_IZABRANI_LIST_REQUEST = "PACIJENT_IZABRANI_LIST_REQUEST";
export const PACIJENT_IZABRANI_LIST_SUCCESS = "PACIJENT_IZABRANI_LIST_SUCCESS";
export const PACIJENT_IZABRANI_LIST_FAIL = "PACIJENT_IZABRANI_LIST_FAIL";



export const PACIJENT_DETAILS_REQUEST = "PACIJENT_DETAILS_REQUEST";
export const PACIJENT_DETAILS_SUCCESS = "PACIJENT_DETAILS_SUCCESS";
export const PACIJENT_DETAILS_FAIL = "PACIJENT_DETAILS_FAIL";



export const PACIJENT_DELETE_REQUEST = "PACIJENT_DELETE_REQUEST";
export const PACIJENT_DELETE_SUCCESS = "PACIJENT_DELETE_SUCCESS";
export const PACIJENT_DELETE_FAIL = "PACIJENT_DELETE_FAIL";
export const PACIJENT_DELETE_RESET = "PACIJENT_DELETE_RESET";



export const PACIJENT_PREBACI_REQUEST = "PACIJENT_PREBACI_REQUEST";
export const PACIJENT_PREBACI_SUCCESS = "PACIJENT_PREBACI_SUCCESS";
export const PACIJENT_PREBACI_RESET = "PACIJENT_PREBACI_RESET";
export const PACIJENT_PREBACI_FAIL = "PACIJENT_PREBACI_FAIL";