export const PACIJENT_ODELJENJA_LIST_REQUEST = "PACIJENT_ODELJENJA_LIST_REQUEST";
export const PACIJENT_ODELJENJA_LIST_SUCCESS = "PACIJENT_ODELJENJA_LIST_SUCCESS";
export const PACIJENT_ODELJENJA_LIST_FAIL = "PACIJENT_ODELJENJA_LIST_FAIL";