export const PREGLED_CREATE_REQUEST = "PREGLED_CREATE_REQUEST";
export const PREGLED_CREATE_SUCCESS = "PREGLED_CREATE_SUCCESS";
export const PREGLED_CREATE_RESET = "PREGLED_CREATE_RESET";
export const PREGLED_CREATE_FAIL = "PREGLED_CREATE_FAIL";